import 'dart:convert';
import 'package:flutter/material.dart';
import 'job_details_page.dart';
import 'app_routes.dart';
import 'bottom_nav.dart';
import 'collect_signature_page.dart';
import 'sharepoint_service.dart';
import 'app_core.dart';

/// Formats a DateTime as "3:45 PM" without needing the intl package.
String formatJobTime(DateTime dt) {
  final period = dt.hour >= 12 ? 'PM' : 'AM';
  int hour12 = dt.hour % 12;
  if (hour12 == 0) hour12 = 12;
  final minute = dt.minute.toString().padLeft(2, '0');
  return '$hour12:$minute $period';
}

/// Formats a DateTime as "31-Dec-2001".
String formatJobDate(DateTime dt) {
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  final day = dt.day.toString().padLeft(2, '0');
  return "$day-${months[dt.month - 1]}-${dt.year}";
}

/// The two job types a manager can pick between when creating a job.
const String jobTypeProject = "Project";
const String jobTypeService = "Service";

/// The icon shown for a job's type — house for Project, tool for
/// Service. Defaults to Project's icon if unset.
IconData jobTypeIcon(String? jobType) {
  return jobType == jobTypeService ? Icons.build : Icons.home_rounded;
}

/// True if [day] falls within a job's scheduled range — a single day if
/// only `expectedDate` is set, or the full span if `endDate` is also set.
bool jobActiveOn(HistoryJob job, DateTime day) {
  if (job.expectedDate == null) return false;
  final start = DateTime(job.expectedDate!.year, job.expectedDate!.month, job.expectedDate!.day);
  final end = job.endDate != null
      ? DateTime(job.endDate!.year, job.endDate!.month, job.endDate!.day)
      : start;
  final d = DateTime(day.year, day.month, day.day);
  return !d.isBefore(start) && !d.isAfter(end);
}

/// Sub-type options shown only when Job Type is jobTypeService.
const String serviceSubTypeService = "Service";
const String serviceSubTypeAfterService = "After Sale Service";
const List<String> serviceSubTypes = [serviceSubTypeService, serviceSubTypeAfterService];

/// The full list of engineers/technicians. Shared between the Assign
/// form (who a job is assigned to) and the Service Form's "Service By"
/// dropdown, so both stay in sync — edit this one list to update both.
const List<String> engineerNames = [
  "Mook",
  "Phannuwat",
  "Reiwat",
  "Min",
];

/// The full set of statuses a job can be in — used to build the filter
/// chips on this page. Includes both statuses generated by the app's own
/// service-job flow (Unassigned/In Progress/Pending Signature/Overdue) and
/// the project-tracking stages imported from the Project List spreadsheet
/// (Not Started Yet/Install Equipment/Piping and Cabling/Commissioning/
/// Pre-Handover) — "Completed" is shared by both.
const List<String> jobStatuses = [
  "Unassigned",
  "Not Started Yet",
  "In Progress",
  "Install Equipment",
  "Piping and Cabling",
  "Commissioning",
  "Pre-Handover",
  "Pending Signature",
  "Completed",
  "Overdue",
];

// "Assigned" isn't a real job.status value (it's derived from assignedTo
// being set), but it's shown as its own bar on the dashboard chart, so it
// needs to be a selectable filter option too. Kept separate from
// [jobStatuses] since that list mirrors the actual status values stored on
// a job.
const List<String> quickStatusFilters = ["Assigned", ...jobStatuses];

/// Matches a job against a quick-filter value from [quickStatusFilters].
/// Handles "Assigned" as a special case (assignedTo != null) since it isn't
/// a real `status` value; everything else is a plain status equality check.
bool jobMatchesStatusFilter(HistoryJob job, String? filter) {
  if (filter == null) return true;
  if (filter == "Assigned") return job.assignedTo != null;
  return job.status == filter;
}

/// Color used for each status bucket, shared by the dashboard's pie chart
/// legend and every status chip in the app — covers both the app's own
/// service-job statuses and the project stages imported from the Project
/// List spreadsheet. Anything not listed here falls back to blueGrey at
/// the call site.
const Map<String, Color> statusChartColors = {
  "Assigned": Color.fromARGB(255, 83, 88, 92),
  "Unassigned": Colors.blueGrey,
  "Not Started Yet": Colors.grey,
  "In Progress": Color.fromARGB(255, 255, 187, 0),
  "Install Equipment": Color(0xFF3F51B5),
  "Piping and Cabling": Color(0xFF8E24AA),
  "Commissioning": Color(0xFF00897B),
  "Pre-Handover": Color(0xFFFF7043),
  "Pending Signature": Color(0xFFFFA726),
  "Completed": Color.fromARGB(255, 35, 163, 89),
  "Overdue": Colors.red,
};

const String _jobsPrefKey = 'created_jobs';

/// A single job/project entry. Used both for the built-in demo rows and
/// for jobs created from the Assign tab.
class HistoryJob {
  final String id;
  String title;
  String subtitle; // shown in list tiles — the location
  String time;
  String status;
  String? assignedTo;
  String? action;
  String? task; // sub-task checklist item, depends on [action]
  String jobType; // jobTypeProject or jobTypeService
  String? serviceSubType; // serviceSubTypeService or serviceSubTypeAfterService, only when jobType == jobTypeService

  // Extra detail captured by the Assign form.
  String? product; // e.g. "KNX F10SW"
  String? description;
  DateTime? expectedDate; // start date when the job spans a range
  DateTime? endDate; // end date of the scheduled range; null = single day
  String? location;

  // Signature tracking — set when the customer wasn't on-site to sign
  // at the time the engineer submitted the service report.
  bool signaturePending;
  DateTime? signatureDueBy;

  // Service report attachments — saved locally (SharedPreferences) as soon
  // as the report is submitted, regardless of whether the SharePoint
  // backend is configured/reachable, so nothing is lost while that's
  // being set up.
  List<String> photoBase64;
  List<String> photoFileNames;
  String? signatureBase64;

  HistoryJob({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.time,
    required this.status,
    this.assignedTo,
    this.action,
    this.task,
    this.jobType = jobTypeProject,
    this.serviceSubType,
    this.product,
    this.description,
    this.expectedDate,
    this.endDate,
    this.location,
    this.signaturePending = false,
    this.signatureDueBy,
    List<String>? photoBase64,
    List<String>? photoFileNames,
    this.signatureBase64,
  })  : photoBase64 = photoBase64 ?? [],
        photoFileNames = photoFileNames ?? [];

  Map<String, dynamic> toJson() => {
        'id': id,
        'title': title,
        'subtitle': subtitle,
        'time': time,
        'status': status,
        'assignedTo': assignedTo,
        'action': action,
        'task': task,
        'jobType': jobType,
        'serviceSubType': serviceSubType,
        'product': product,
        'description': description,
        'expectedDate': expectedDate?.toIso8601String(),
        'endDate': endDate?.toIso8601String(),
        'location': location,
        'signaturePending': signaturePending,
        'signatureDueBy': signatureDueBy?.toIso8601String(),
        'photoBase64': photoBase64,
        'photoFileNames': photoFileNames,
        'signatureBase64': signatureBase64,
      };

  factory HistoryJob.fromJson(Map<String, dynamic> json) => HistoryJob(
        id: json['id'] as String,
        title: json['title'] as String,
        subtitle: json['subtitle'] as String,
        time: json['time'] as String,
        status: json['status'] as String,
        assignedTo: json['assignedTo'] as String?,
        action: json['action'] as String?,
        task: json['task'] as String?,
        jobType: json['jobType'] as String? ?? jobTypeProject,
        serviceSubType: json['serviceSubType'] as String?,
        product: json['product'] as String?,
        description: json['description'] as String?,
        expectedDate: json['expectedDate'] != null ? DateTime.tryParse(json['expectedDate'] as String) : null,
        endDate: json['endDate'] != null ? DateTime.tryParse(json['endDate'] as String) : null,
        location: json['location'] as String?,
        signaturePending: json['signaturePending'] as bool? ?? false,
        signatureDueBy: json['signatureDueBy'] != null ? DateTime.tryParse(json['signatureDueBy'] as String) : null,
        photoBase64: (json['photoBase64'] as List?)?.map((e) => e as String).toList(),
        photoFileNames: (json['photoFileNames'] as List?)?.map((e) => e as String).toList(),
        signatureBase64: json['signatureBase64'] as String?,
      );
}

class JobHistoryPage extends StatefulWidget {
  const JobHistoryPage({super.key});

  // Built-in demo rows, always shown.
  static final List<HistoryJob> _demoJobs = [
    HistoryJob(id: "d1", title: "Kansi", subtitle: "Room 501 · AC Service", time: "10:00 AM", status: "Completed"),
    HistoryJob(id: "d2", title: "Adam", subtitle: "Room 320 · Lighting Maintenance", time: "02:00 PM", status: "Completed"),
    HistoryJob(id: "d3", title: "Buugan", subtitle: "Room 1208 · Switch Socket Issue", time: "04:30 PM", status: "In Progress"),
    HistoryJob(id: "d4", title: "Nara", subtitle: "Room 210 · Plumbing Check", time: "09:15 AM", status: "Completed"),
    HistoryJob(id: "d5", title: "Somchai", subtitle: "Room 88 · Elevator Inspection", time: "01:00 PM", status: "Overdue"),

    // Imported from Project_list.csv (Project Name / Sales Order Number /
    // Current Progress columns) — real projects, shown alongside the demo
    // service jobs above so the dashboard/task list reflects actual data.
    HistoryJob(id: "p1", title: "ADAM Showroom", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p2", title: "Baan K.Nink 99/215", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p3", title: "Let's Relax Ratchadamri", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p4", title: "Anantara Chiang Mai Mockup Room", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p5", title: "S38 Black Box", subtitle: "Project", time: "", status: "Install Equipment", jobType: jobTypeProject),
    HistoryJob(id: "p6", title: "Malton Gate 18/36", subtitle: "Project", time: "", status: "Commissioning", jobType: jobTypeProject),
    HistoryJob(id: "p7", title: "Tela Thonglor", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p8", title: "Meka Ramintra", subtitle: "Project", time: "", status: "Commissioning", jobType: jobTypeProject),
    HistoryJob(id: "p9", title: "Como Metropolitan Bangkok", subtitle: "Project", time: "", status: "Not Started Yet", jobType: jobTypeProject),
    HistoryJob(id: "p10", title: "ADAM's Booth", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p11", title: "Banyan tree hotel renovation RCU system", subtitle: "Project", time: "", status: "Not Started Yet", jobType: jobTypeProject),
    HistoryJob(id: "p12", title: "Kansi House", subtitle: "Project", time: "", status: "Piping and Cabling", jobType: jobTypeProject),
    HistoryJob(id: "p13", title: "Baanlaesuan Adam", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p14", title: "Baan K.Ae", subtitle: "Project", time: "", status: "Pre-Handover", jobType: jobTypeProject),
    HistoryJob(id: "p15", title: "Baan K.North - Grand Residence", subtitle: "Project", time: "", status: "Install Equipment", jobType: jobTypeProject),
    HistoryJob(id: "p16", title: "Baan K.Yhok - Grand Canel", subtitle: "Project", time: "", status: "Install Equipment", jobType: jobTypeProject),
    HistoryJob(id: "p17", title: "Baan K.Job - Golden Lanna", subtitle: "Project", time: "", status: "Install Equipment", jobType: jobTypeProject),
    HistoryJob(id: "p18", title: "SKV51 Public Area", subtitle: "Project", time: "", status: "Not Started Yet", jobType: jobTypeProject),
    HistoryJob(id: "p19", title: "SKV51", subtitle: "Project", time: "", status: "Not Started Yet", jobType: jobTypeProject),
    HistoryJob(id: "p20", title: "BuGaan Pattanakarn (No.16)", subtitle: "Project", time: "", status: "Commissioning", jobType: jobTypeProject),
    HistoryJob(id: "p21", title: "K.Pimtha House", subtitle: "Project", time: "", status: "Install Equipment", jobType: jobTypeProject),
    HistoryJob(id: "p22", title: "Casambi Dicussion", subtitle: "Project", time: "", status: "Completed", jobType: jobTypeProject),
    HistoryJob(id: "p23", title: "Baan K.Prasit", subtitle: "Project", time: "", status: "Piping and Cabling", jobType: jobTypeProject),
    HistoryJob(id: "p24", title: "Project Testing", subtitle: "Project", time: "", status: "Not Started Yet", jobType: jobTypeProject),
    HistoryJob(id: "p25", title: "Tonson", subtitle: "Project", time: "", status: "Commissioning", jobType: jobTypeProject),
    HistoryJob(id: "p26", title: "Adam Baanlaesuan", subtitle: "Project", time: "", status: "Commissioning", jobType: jobTypeProject),
    HistoryJob(id: "p27", title: "Sansiri Chidlom - Mockup Room", subtitle: "Project", time: "", status: "Piping and Cabling", jobType: jobTypeProject),
  ];

  // Jobs created/edited from the Assign tab. Shared across the app.
  static final ValueNotifier<List<HistoryJob>> createdJobsNotifier =
      ValueNotifier<List<HistoryJob>>([]);

  static List<HistoryJob> get createdJobs => createdJobsNotifier.value;

  /// Every job the app knows about — freshly created/assigned ones first,
  /// followed by the built-in demo rows. Used by the Dashboard so it
  /// reflects real jobs instead of a fixed set of sample cards.
  static List<HistoryJob> get allJobs => [
        ...createdJobsNotifier.value,
        ..._demoJobs,
      ];

  /// Restores created jobs saved from a previous session. Call once at
  /// startup, after AppStorage.init().
  static void loadSaved() {
    final raw = AppStorage.prefs.getString(_jobsPrefKey);
    if (raw == null) return;
    try {
      final decoded = jsonDecode(raw) as List;
      createdJobsNotifier.value =
          decoded.map((e) => HistoryJob.fromJson(e as Map<String, dynamic>)).toList();
    } catch (_) {
      // Corrupt or outdated saved data — start fresh rather than crash.
    }
  }

  static void _persist() {
    final encoded = jsonEncode(createdJobsNotifier.value.map((j) => j.toJson()).toList());
    AppStorage.prefs.setString(_jobsPrefKey, encoded);
  }

  /// Adds a newly-created job (from Assign > Create) and shows it here.
  static HistoryJob addJob({
    required String title,
    String jobType = jobTypeProject,
    String? serviceSubType,
    String? product,
    String? description,
    DateTime? expectedDate,
    DateTime? endDate,
    String? location,
    String? assignedTo,
    String? action,
    String? task,
  }) {
    final job = HistoryJob(
      id: DateTime.now().microsecondsSinceEpoch.toString(),
      title: title,
      subtitle: location ?? "",
      time: expectedDate != null ? formatJobTime(expectedDate) : formatJobTime(DateTime.now()),
      status: action ?? "Unassigned",
      assignedTo: assignedTo,
      action: action,
      task: task,
      jobType: jobType,
      serviceSubType: serviceSubType,
      product: product,
      description: description,
      expectedDate: expectedDate,
      endDate: endDate,
      location: location,
    );
    createdJobsNotifier.value = [job, ...createdJobsNotifier.value];
    _persist();
    return job;
  }

  /// Updates an existing created job (from Assign editing an entry).
  static void updateJob(
    String id, {
    required String title,
    String jobType = jobTypeProject,
    String? serviceSubType,
    String? product,
    String? description,
    DateTime? expectedDate,
    DateTime? endDate,
    String? location,
    String? assignedTo,
    String? action,
    String? task,
  }) {
    for (final j in createdJobsNotifier.value) {
      if (j.id == id) {
        j.title = title;
        j.jobType = jobType;
        j.serviceSubType = serviceSubType;
        j.product = product;
        j.description = description;
        j.expectedDate = expectedDate;
        j.endDate = endDate;
        j.location = location;
        j.subtitle = location ?? "";
        j.time = expectedDate != null ? formatJobTime(expectedDate) : j.time;
        j.assignedTo = assignedTo;
        j.action = action;
        j.task = task;
        j.status = action ?? "Unassigned";
        break;
      }
    }
    createdJobsNotifier.value = [...createdJobsNotifier.value];
    _persist();
  }

  /// Finds a job by id across both demo rows and created jobs.
  static HistoryJob? findJob(String id) {
    for (final j in [..._demoJobs, ...createdJobsNotifier.value]) {
      if (j.id == id) return j;
    }
    return null;
  }

  /// Called when a service report is submitted without the customer's
  /// signature (they weren't on-site). Flags the job so it shows up as
  /// needing a signature, due by the end of today.
  static void markPendingSignature(String id) {
    final job = findJob(id);
    if (job == null) return;
    final now = DateTime.now();
    job.signaturePending = true;
    job.signatureDueBy = DateTime(now.year, now.month, now.day, 23, 59);
    job.status = "Pending Signature";
    _refresh();
  }

  /// Called once the engineer goes back and actually collects the
  /// customer's signature for a job that was previously pending.
  static void markSignatureCollected(String id, {String? signatureBase64}) {
    final job = findJob(id);
    if (job == null) return;
    job.signaturePending = false;
    job.signatureDueBy = null;
    job.status = "Completed";
    if (signatureBase64 != null) {
      job.signatureBase64 = signatureBase64;
    }
    _refresh();
  }

  /// Saves the submitted service report's photos/signature onto the job
  /// locally (SharedPreferences), independent of whether the SharePoint
  /// backend upload succeeds. This means nothing is lost while the backend
  /// isn't configured yet.
  static void attachReportPhotos(
    String id, {
    required List<String> photoBase64,
    required List<String> photoFileNames,
    String? signatureBase64,
  }) {
    final job = findJob(id);
    if (job == null) return;
    job.photoBase64 = photoBase64;
    job.photoFileNames = photoFileNames;
    if (signatureBase64 != null) {
      job.signatureBase64 = signatureBase64;
    }
    _refresh();
  }

  /// Called when the engineer finishes a service report on-site (customer
  /// signed immediately, no remote signature needed). Marks the job done
  /// so it can't be started again until the manager re-assigns it.
  static void markCompleted(String id) {
    final job = findJob(id);
    if (job == null) return;
    job.signaturePending = false;
    job.signatureDueBy = null;
    job.status = "Completed";
    _refresh();
  }

  /// Forces listeners to rebuild — needed even when only a demo job's
  /// mutable fields changed, since they aren't part of the notifier's list.
  static void _refresh() {
    createdJobsNotifier.value = [...createdJobsNotifier.value];
    _persist();
  }

  @override
  State<JobHistoryPage> createState() => _JobHistoryPageState();
}

class _JobHistoryPageState extends State<JobHistoryPage> {
  final _searchController = TextEditingController();
  String _query = "";
  String? _statusFilter; // null = All

  @override
  void initState() {
    super.initState();
    AppLocale.languageNotifier.addListener(_onLanguageChanged);
    _searchController.addListener(() {
      setState(() => _query = _searchController.text.trim().toLowerCase());
    });
  }

  @override
  void dispose() {
    AppLocale.languageNotifier.removeListener(_onLanguageChanged);
    _searchController.dispose();
    super.dispose();
  }

  void _onLanguageChanged() => setState(() {});

  List<HistoryJob> _filteredJobs(List<HistoryJob> created) {
    final jobs = [...created, ...JobHistoryPage._demoJobs];
    return jobs.where((job) {
      final matchesStatus = jobMatchesStatusFilter(job, _statusFilter);
      final matchesQuery = _query.isEmpty ||
          job.title.toLowerCase().contains(_query) ||
          job.subtitle.toLowerCase().contains(_query) ||
          (job.assignedTo?.toLowerCase().contains(_query) ?? false);
      return matchesStatus && matchesQuery;
    }).toList();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: bgGray,
      appBar: AppBar(
        backgroundColor: navy,
        elevation: 0,
        title: Text(tr("Job History"), style: const TextStyle(color: Colors.white)),
        iconTheme: const IconThemeData(color: Colors.white),
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.only(
            bottomLeft: Radius.circular(20),
            bottomRight: Radius.circular(20),
          ),
        ),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
            child: Container(
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(14),
                boxShadow: [
                  BoxShadow(color: Colors.black.withValues(alpha: 0.04), blurRadius: 10, offset: const Offset(0, 3)),
                ],
              ),
              child: TextField(
                controller: _searchController,
                decoration: InputDecoration(
                  hintText: tr("Search jobs"),
                  hintStyle: const TextStyle(color: Colors.black38, fontSize: 14),
                  prefixIcon: const Icon(Icons.search, color: navy, size: 20),
                  suffixIcon: _query.isEmpty
                      ? null
                      : IconButton(
                          icon: const Icon(Icons.close, size: 18, color: Colors.black45),
                          onPressed: () => _searchController.clear(),
                        ),
                  border: InputBorder.none,
                  contentPadding: const EdgeInsets.symmetric(vertical: 14, horizontal: 4),
                ),
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.fromLTRB(20, 4, 20, 4),
            child: _statusFilterDropdown(),
          ),
          const SizedBox(height: 8),
          Expanded(
            child: ValueListenableBuilder<List<HistoryJob>>(
              valueListenable: JobHistoryPage.createdJobsNotifier,
              builder: (context, created, _) {
                final jobs = _filteredJobs(created);
                return RefreshIndicator(
                  color: navy,
                  onRefresh: () async {
                    // No live backend to re-fetch from yet — this simply
                    // gives the list a moment to visually refresh so the
                    // gesture always feels responsive.
                    await Future.delayed(const Duration(milliseconds: 600));
                  },
                  child: jobs.isEmpty
                      ? ListView(
                          padding: const EdgeInsets.all(20),
                          children: [
                            const SizedBox(height: 80),
                            const Icon(Icons.search_off, size: 40, color: Colors.black26),
                            const SizedBox(height: 10),
                            Center(
                              child: Text(
                                tr("No jobs match your search"),
                                style: const TextStyle(color: Colors.black45, fontWeight: FontWeight.w600),
                              ),
                            ),
                          ],
                        )
                      : ListView.separated(
                          padding: const EdgeInsets.fromLTRB(20, 4, 20, 20),
                          itemCount: jobs.length,
                          separatorBuilder: (_, __) => const SizedBox(height: 12),
                          itemBuilder: (context, index) => _jobTile(context, jobs[index]),
                        ),
                );
              },
            ),
          ),
        ],
      ),
      bottomNavigationBar: const AppBottomNav(current: NavTab.projects),
    );
  }

  Widget _statusFilterDropdown() {
    return Align(
      alignment: Alignment.centerRight,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          Text(
            tr("Project Status"),
            style: const TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: Colors.black45),
          ),
          const SizedBox(height: 4),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.black.withValues(alpha: 0.1)),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(Icons.filter_list, size: 16, color: navy),
                const SizedBox(width: 4),
                DropdownButtonHideUnderline(
                  child: DropdownButton<String?>(
                    value: _statusFilter,
                    dropdownColor: Colors.white,
                    itemHeight: 56,
                    icon: const Icon(Icons.keyboard_arrow_down, size: 18, color: navy),
                    style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: Colors.black87),
                    borderRadius: BorderRadius.circular(12),
                    items: [
                      DropdownMenuItem<String?>(
                        value: null,
                        child: Padding(
                          padding: const EdgeInsets.symmetric(vertical: 4),
                          child: Text(tr("All")),
                        ),
                      ),
                      for (final s in quickStatusFilters)
                        DropdownMenuItem<String?>(
                          value: s,
                          child: Padding(
                            padding: const EdgeInsets.symmetric(vertical: 4),
                            child: Text(tr(s)),
                          ),
                        ),
                    ],
                    onChanged: (value) => setState(() => _statusFilter = value),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _jobTile(BuildContext context, HistoryJob job) {
    return InkWell(
      borderRadius: BorderRadius.circular(16),
      onTap: () {
        Navigator.push(
          context,
          AppRoute.to(
            JobDetailsPage(
              title: job.title,
              subtitle: job.subtitle,
              time: job.time,
              jobId: job.id,
              heroTag: 'job-icon-${job.id}',
            ),
          ),
        );
      },
      child: Container(
        padding: const EdgeInsets.all(14),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withValues(alpha: 0.04),
              blurRadius: 10,
              offset: const Offset(0, 3),
            ),
          ],
        ),
        child: Row(
          children: [
            Hero(
              tag: 'job-icon-${job.id}',
              child: Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: navy.withValues(alpha: 0.08),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(jobTypeIcon(job.jobType), color: navy),
              ),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    job.title,
                    style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    job.subtitle,
                    style: const TextStyle(fontSize: 12, color: Colors.black54),
                  ),
                  const SizedBox(height: 6),
                  Row(
                    children: [
                      _statusChip(job.status),
                      const SizedBox(width: 6),
                      const Icon(Icons.access_time, size: 12, color: Colors.black38),
                      const SizedBox(width: 4),
                      Text(
                        job.time,
                        style: const TextStyle(fontSize: 11, color: Colors.black45),
                      ),
                    ],
                  ),
                  if (job.assignedTo != null) ...[
                    const SizedBox(height: 4),
                    Row(
                      children: [
                        const Icon(Icons.person_outline, size: 12, color: Colors.black38),
                        const SizedBox(width: 4),
                        Text(
                          job.assignedTo!,
                          style: const TextStyle(fontSize: 11, color: Colors.black45),
                        ),
                      ],
                    ),
                  ],
                  if (job.signaturePending) ...[
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        const Icon(Icons.edit_note, size: 14, color: Colors.orange),
                        const SizedBox(width: 4),
                        Expanded(
                          child: Text(
                            tr("Awaiting customer signature — due today"),
                            style: const TextStyle(fontSize: 11, color: Colors.orange, fontWeight: FontWeight.w600),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 4),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        TextButton(
                          style: TextButton.styleFrom(
                            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                            minimumSize: Size.zero,
                            tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                          ),
                          onPressed: () => _checkSignatureStatus(context, job),
                          child: Text(tr("Check Status"), style: const TextStyle(color: Colors.black54, fontSize: 11, fontWeight: FontWeight.w600)),
                        ),
                        const SizedBox(width: 4),
                        TextButton(
                          style: TextButton.styleFrom(
                            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                            minimumSize: Size.zero,
                            tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                          ),
                          onPressed: () {
                            Navigator.push(
                              context,
                              AppRoute.to(CollectSignaturePage(jobId: job.id, jobTitle: job.title)),
                            );
                          },
                          child: Text(tr("Get Signature"), style: const TextStyle(color: navy, fontSize: 11, fontWeight: FontWeight.w700)),
                        ),
                      ],
                    ),
                  ],
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _checkSignatureStatus(BuildContext context, HistoryJob job) async {
    if (!SharePointService.isSignatureLinkConfigured) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(tr("Signature-link flow isn't configured yet — see sharepoint_service.dart"))),
      );
      return;
    }

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(tr("Checking..."))),
    );

    final signatureBase64 = await SharePointService.checkSignatureStatus(job.id);

    if (signatureBase64 != null) {
      JobHistoryPage.markSignatureCollected(job.id);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(tr("Customer has signed — job marked complete"))),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(tr("Not signed yet"))),
      );
    }
  }

  Widget _statusChip(String status) {
    final color = statusChartColors[status] ?? Colors.blueGrey;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Text(
        tr(status),
        style: TextStyle(fontSize: 10, color: color, fontWeight: FontWeight.w600),
      ),
    );
  }
}